name: SonarQube test
description: "Reusable action to run SonarQube Analysis for Python code"
author: "Sebastian Nedelcu"

on:
  workflow-call:
    inputs: 
      python-version:
        description: "The Python version that is used on the repository"
        required: true
      requirements-file:
        description: "The name of the requirements file to be installed"
        required: true
      sq-project:
        description: "SonarQube project's unique identifier"
        required: true
      sq-organization:
        description: "SonarQube organization's unique identifier"
        required: true
      sq-token:
        description: "SonarQube access token"
        required: true

jobs:
  analyze:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ inputs.requirements-file }}
          pip install coverage pytest

      - name: Cache SonarScanner CLI
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Download SonarScanner CLI
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner-cli-*.zip
          mv sonar-scanner-* sonar-scanner
          echo "$(pwd)/sonar-scanner/bin" >> $GITHUB_PATH

      - name: Run tests and generate coverage
        run: |
          coverage run -m pytest
          coverage xml -o "coverage.xml"

      - name: Run SonarScanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=${{ inputs.sonar-project-key }} \
            -Dsonar.organization=${{ inputs.sonar-org }} \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.python.coverage.reportPaths=${{ inputs.coverage-file }}
