name: SonarQube test
description: "Reusable action to run SonarQube Analysis for Python code"
author: "Sebastian Nedelcu"

inputs:
  sq-project:
    description: "SonarQube project's unique identifier"
    required: true
  sq-organization:
    description: "SonarQube organization's unique identifier"
    required: true
  sq-token:
    description: "SonarQube access token"
    required: true
  coverage-report-path:
    description: "The path to the coverage report"
    required: true
  coverage-exclusions:
    description: "The paths (comma-delimited) of the files / directories to exclude from the code covarege"
    required: false
    default: ""
  coverage-type:
    description: "The type of the coverage report. Allowed values: python, csharp"
    required: true
  sources:
    description: "The sources"
    required: false
    default: "."
        
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build Sonar coverage args
      id: coverage-args
      shell: bash
      run: |
        case "${{ inputs.coverage-type }}" in
          python)
            echo "COVERAGE_ARG=-Dsonar.python.coverage.reportPaths=${{ inputs.coverage-report-path }}" >> "$GITHUB_OUTPUT"
            ;;
          cshap)
            echo "COVERAGE_ARG=-Dsonar.cs.vscoveragexml.reportsPaths=${{ inputs.coverage-report-path }}" >> "$GITHUB_OUTPUT"
            ;;
          *)
            echo "Unsupported coverage type: ${{ inputs.coverage-type }}"
            exit 1
            ;;
        esac
        
    - name: Run SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v6
      env:
        SONAR_TOKEN: ${{ inputs.sq-token }}
      with:
        args: >
          -Dsonar.projectKey=${{ inputs.sq-project }}
          -Dsonar.organization=${{ inputs.sq-organization }}
          -Dsonar.sources=${{ inputs.sources }}
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.token=${{ inputs.sq-token }}
          -Dsonar.coverage.exclusions=${{ inputs.coverage-exclusions }}
          ${{ steps.coverage-args.outputs.COVERAGE_ARG }}
